peer_detector_node:
  ros__parameters:
    marker_R: 0.1016 #meters, 4 in
    camera_num: 3
    lower_color: [160, 0, 0] #HSV
    upper_color: [180, 255, 255] #HSV
    detection_frequency: 3.0 #Hz
    cameras:
      # fov in deg
      # heading in deg, front 0, right hand coordinates
      # position in m, robot centric
      cam1:
        topic_name: "/camera1/image_raw"
        fov: 90.0
        heading: 0.0
        resolution: [320, 240]
        position: [0.0, 0.0, 0.0]